### ISSUE TITLE
Invalid link for the offline dataset

### ISSUE THREAD

**Issue by aithlab** [ReinholdM/Offline-Pre-trained-Multi-Agent-Decision-Transformer#3]
Thanks to share your code for the interesting paper.
I've tried to run your code by following the procedure written in README. 
However, the link to get the offline dataset for SMAC is not working.
Could you update the link? or is there any other link to download the dataset? 

Regards,

**Comment by ReinholdM** [comment]
Thank you for your interest in our work. Sorry the previous link has expired, you can download our dataset from [here](https://cowtransfer.com/s/3785a6a9e5d044)

**Comment by wang88256187** [comment]
why just 2GB? The datasets should be very large?

**Comment by shahaamirbader** [comment]
> why just 2GB? The datasets should be very large?

Its actually 44 GB, once you extract it. Mind you it needs to be extracted twice.
