### ISSUE TITLE
Obs and State dims in offline datasets are different from SC2ENV

### ISSUE THREAD

**Issue by RZ-Q** [ReinholdM/Offline-Pre-trained-Multi-Agent-Decision-Transformer#8]
I have checked datas in your offline datasets, and I found that the dims of obs and state are different from SC2 env. For example, in 3s5z map, the obs of an agent should be 150 dims(128 dims without last action and onehot id), but in your datasets, the obs dim is 252.
Could you give me some explaination?

**Comment by RZ-Q** [comment]
OK, this offline datasets have added more infomation from the env.
sc2/envs/starcraft2/StarCraft2_Env.py

**Comment by shahaamirbader** [comment]
> I have checked datas in your offline datasets, and I found that the dims of obs and state are different from SC2 env. For example, in 3s5z map, the obs of an agent should be 150 dims(128 dims without last action and onehot id), but in your datasets, the obs dim is 252. Could you give me some explaination?

Hi, can you give more details as to how you were able to resolve this issue of dimension mismatch?

**Comment by RZ-Q** [comment]
em....，you can check out the samc env codes in sc2/envs/starcraft2/StarCraft2_Env.py. As in pymarl (or how to say, the origin smac env codes), some configs are truned to False while True in this env version. More, the author add additional information in the state and obs. You can just figre out the order of features in obs and state by comparing this version and origin samc, filter out the features you donot need. Hope this can help you.
